# Standard rustfmt configuration for the Beggar project
# Learn more: https://rust-lang.github.io/rustfmt/

# Basic settings
max_width = 100
tab_spaces = 4
hard_tabs = false
edition = "2021"

# Imports and modules
imports_granularity = "Crate"
group_imports = "StdExternalCrate"
reorder_imports = true
reorder_modules = true

# Code structure
format_code_in_doc_comments = true
format_macro_bodies = true
format_macro_matchers = true
format_strings = true
wrap_comments = true

# Function calls and arguments
fn_args_layout = "Tall" # Arguments in function calls are laid out according to their density.
overflow_delimited_expr = true # Deeply nested arguments of function calls are identified and laid out according to their density.
use_small_heuristics = "Default"
where_single_line = false

# Braces and blocks
control_brace_style = "AlwaysSameLine"
empty_item_single_line = true
brace_style = "SameLineWhere"

# Consistency
merge_derives = true
newline_style = "Unix"
use_field_init_shorthand = true
