name: Security Audit

on:
  schedule:
    - cron: '0 0 * * *'  # Runs at midnight every day
  push:
    paths: 
      - '**/Cargo.toml'
      - '**/Cargo.lock'

jobs:
  audit:
    name: Security Audit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Rust Audit
        uses: actions-rs/audit-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
